owner: rdd-giga
repo: reset-status-page

sites:
  - name: RESET Site
    url: https://reset.build
  - name: RESET Assessment
    url: https://assessment.reset.build
  - name: RESET Cloud
    url: https://cloud.reset.build

status-website:
  baseUrl: /reset-status-page
  name: RESET Status Page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
