owner: rdd-giga
repo: reset-status-page

sites:
  - name: RESET Site
    url: https://reset.build
  - name: RESET Assessment
    url: https://assessment.reset.build
  - name: RESET Cloud
    url: https://cloud.reset.build
  - name: RESET Socket API
    url: https://reset.build
    port: 8069
    check: "tcp-ping"

assignees:
  - serco-chen
  - charleschu

status-website:
  # baseUrl: /reset-status-page
  name: RESET Status Page
  cname: status.reset.build
  introTitle: "**RESET** is a set of standards and assessment tools & services to develop actionable, long term strategies towards health and sustainability for the built environment."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/rdd-giga/reset-status-page).
  navbar:
    - title: Status
      href: /
    - title: RESET Official Site
      href: https://reset.build
